assets/scss/common/_grid.scss, assets/scss/common/_post.scss, assets/scss/common/_typography.scss, assets/scss/common/_variables.scss, assets/scss/home.scss, content/_index.md, layouts/shortcodes/latestposts.html
This PR adds 3 blog posts to the front page and restyles the grid view to match.
=> Adding 3 blog posts to front page

assets/scss/bio.scss, layouts/_default/single.html
This PR adds author bios to the end of posts.
=> Added author bios to posts

content/blog/2020-10-23-mayastor-lightning-fast-storage-for-kubernetes.md
Signed-off-by: Janos Pasztor <janos@pasztor.at>
=> Transscribed mayastor article YAML from pictures to text

.github/workflows/deploy.yml
Signed-off-by: Janos Pasztor <janos@pasztor.at>
=> This change adds an hourly rebuild to update the forum posts

.github/workflows/pr.yaml
Signed-off-by: Janos Pasztor <janos@pasztor.at>
=> Added running Hugo build for PRs

content/contribute/coc.md
Updated rules to include malicious activity and technical disruptions
=> Update to COC Rules

assets/scss/bio.scss, layouts/blog/single.html
This PR fixes the mobile bio.
Before:
After:
=> Fixed mobile bio

content/projects/pmm.md
There is no such page in pmm2, but it's better not to link to pmm1 as it's old
=> Replace pmm1 link

content/contribute/engineeringmeetings/2021-06-29.md
Agenda exporters community meeting №2 June 29, 2021
=> Agenda exporters community meeting 2

content/blog/2021-07-21-create-your-own-exporter-in-go.md
A slight change in Dongchan Sung's article
=> Dongchan: titles and date have been corrected

content/authors/dongchan_sung/_index.md, content/blog/2021-07-21-create-your-own-exporter-in-go.md
Pull the Main branch, and modified my post and author info.
=> Modify blog content

content/podcasts/30.md
the former description was with Karthik which is for Ep. 29
=> description update

content/blog/2021-07-22-lets-be-insync.md
Thanks for feedback. Corrections made.
=> corrections to delete and missed link added.

content/contribute/engineeringmeetings/2021-07-29.md
Add link to meeting notes template
=> Add link to meeting notes

content/podcasts/32.md
Adding transcript for 32 episode
=> Add transcrypt for 32 episode

content/contribute/engineeringmeetings/2021-08-31.md
@percona-csalguero @adivinho Any ideas?
=> Agenda for next community meeting

config.yaml, content/contribute/_index.md, content/contribute/documentation/_index.md, content/contribute/documentation/locations.md
Added new pages that provide some more detailed information on how to contribute to our documentation.
Signed-off-by: Lenz Grimmer <lenz.grimmer@percona.com>
=> Added new Documentation section

content/contribute/documentation/locations.md
Fixed link to the PMM docs (pointed to percona-toolkit doc sources by accident)
Thanks to @atymchuk for pointing this out.
Signed-off-by: Lenz Grimmer <lenz.grimmer@percona.com>
=> locations.md: Fixed PMM docs github link

content/contribute/documentation/locations.md
Updated product documentation location page:
- Updated URLs of docs that migrated to docs.percona.com
- Added column with links to individual contributing docs
Signed-off-by: Lenz Grimmer <lenz.grimmer@percona.com>
=> `locations.md`: Updated URLs, added contrib doc links

config.yaml, content/contribute/surveys.md
Add Testimonials And Surveys page
=> Add Testimonials And Surveys

content/blog/2022-01-27-5-steps-to-improve-performance-of-default-mysql-installation.md
=> Correct 5 steps blog post

content/events/percona-meetups/2022-03-02-percona-meetup-postgresql-operator.md
I have to change the front matters of the meetup March 2nd in order to put the MeetUp of March 10th on top of the list
I will add transcript later. I am working on it now
=> edit front matters waiting for transcript

content/speakers/anton_bystrov/index.md
Update profile for Anton Bystrov
=> Add more LI profiles

content/contribute/articles.md
@dbazhenov I added the article I wrote on Dev as your suggestion 😃
=> Add article my first month in percona

content/authors/kai_wagner/index.md
Signed-off-by: Kai Wagner <kai.wagner@percona.com>
=> Minor fixes author Kai Wagner

content/contribute/documentation/_index.md, content/contribute/documentation/locations.md
Updated the links to the documentation git repositories in `locations.md` and updated the instructions on how to contribute to our docs.
Signed-off-by: Lenz Grimmer <lenz.grimmer@percona.com>
=> Updated documentation locations

content/contribute/help-wanted.md
Added a link to the topics anyone contributing with videos could talk about
=> Video section updated

content/blog/2022-04-05-pi-bullseye-percona-server-64.md
Made updates for version 8.0.29, cleaned up text and grammar errors.
=> Percona server8.0.29 updates

content/blog/2023/2023-03-06-monitor-databaes-open-source-tools.md, content/blog/2023/2023-03-10-backups-for-mysql-with-mysqldump.md
=> Fixed issue

content/contribute/documentation/locations.md
Add a link to the ProxySQL documentation contributing document.
=> locations.md: Add missing link

content/blog/2023/2023-06-19-percona-university-peru.md
=> Added slides for blog Percona University Peru

CONTRIBUTING.md, content/events/streams-monthly-dev/2022-10-27-develop-code.md
- Hi Daniil fixing URL sintax.  Thanks, Pavel Tankov for reporting this issue.
=> Fix Video URL and emphasizing hugo command

content/blog/2023/2023-08-15-pi-arm-pmm.md
=> clean up verbiage

content/blog/2023/2023-10-24-kcduk-cilium-ebpf.md
Hi, @dbazhenov I am adding some links in the footer of this blog post.
Appreciate your support in merging it!
=> Add Links in the footer of the blog

content/blog/2023/2023-12-06-2-41-0-preview.md
Adding PMM 2.41 Tech Preview Blogpost
=> PMM 2.41 Tech Preview Blogpost

content/contribute/articles.md
- Hi Daniil, I added more community members' articles
=> Added more 2023 articles

content/authors/sergey_pronin/index.md, content/blog/2024/2024-01-10-article-dokc-initiatives.md
Improve the call for action of this article and addig Sergey as an author
=> Improve Article

content/blog/2024/2024-03-26-mongodb-open-door.md
Hi Daniil, new blog post about Open MongoDB Doors
=> Blog post MongoDB Open Door

content/blog/2025/2025-05-27-PostgreSQL_18_-_top_enterprise_features_(fast_read).md
Added a blog about PG18 new features
=> Pg18blogpost
